### PR TITLE
GitHub issue #8 and couple of minor changes

### PR DESCRIPTION
**Pull request by ohhai**

### CODE REVIEW

**Comment by ckuhl** [comment]
Maybe it's just my browser, but `image_blocked.svg` and `image.svg` look the same to me - is it different on your end? Aside from that the pull request looks good 👍

**Comment by ohhai** [comment]
Yes, I saw it in other viewers--related to "X" is a font char, I think. You could open it with any editor, I used Inkscape (or convert via imagemagick), X should be present for these cases.

**Comment by ckuhl** [comment]
I see now. However testing it on Ubuntu on Windows 10, it mangles the images when it converts them to png:

image_blocked-256

**Comment by ohhai** [comment]
Wow.
Does it happen with original Ionicons image?
As for Ubuntu on Windows — you mean virtual machine (VirtualBox?)

**Comment by ckuhl** [comment]
The original icon is fine in all of it's sizes, and all of the blocked images are similarly distorted

image

Running `convert --version` I see that I am running ImageMagick 6.8.9-9. What version are you running?


About [Ubuntu on Windows](https://www.microsoft.com/en-us/store/p/ubuntu/9nblggh4msv6), it's a translation layer for linux syscalls(?)

**Comment by ohhai** [comment]
Oh. My hope was that it's not that case (official Ubuntu from Microsoft).

I use ImageMagick 6.9.9.22 from Fedora repos.
Can verify on Ubuntu 16.04 LTS (this version is pointed by the link to MS store), but does it have a sense?
I mean, if you use this ubuntu-on-windows as main development environment.

Tried a common alternative tool advised in internets: rsvg.
But it just ignores 'X' as in previous cases.

Workaround might be to convert X to a vector object, not text.
It might remove all the issues and it's not hard to re-create it as text if necessary.
I'm attaching such a SVG (gzipped, github does want it plain).
[image_blocked_notext.svg.gz](https://github.com/ckuhl/ImageBlockX/files/1563319/image_blocked_notext.svg.gz)

**Comment by ckuhl** [comment]
That new version does the trick! Commit it in and I'll merge in this request 👍

**Comment by ohhai** [comment]
Updated.

**Review by ckuhl — APPROVED** [review]

**Comment by ckuhl** [comment]
It's been merged in, packaged, and uploaded to AMO! If you update your addons now you should see your new icon 😄

**Comment by ohhai** [comment]
Updated, see it, thanks a lot!

**Pull request merged**
